## Recommendation System

## Build a recommender system by using cosine simillarties score for book Data

## Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import pairwise_distances

In [ ]:
book_data= pd.read_csv('/content/book.csv',encoding='cp437')
book_data

      Unnamed: 0  ...  Book.Rating
0              1  ...            5
1              2  ...            3
2              3  ...            6
3              4  ...            8
4              5  ...            6
...          ...  ...          ...
9995        9996  ...            7
9996        9997  ...            9
9997        9998  ...            7
9998        9999  ...            8
9999       10000  ...            6

[10000 rows x 4 columns]

## Data understanding

In [ ]:
book_data = book_data.drop(columns =['Unnamed: 0'])
book_data.head()

   User.ID                                         Book.Title  Book.Rating
0   276726                                Classical Mythology            5
1   276729                                       Clara Callan            3
2   276729                               Decision in Normandy            6
3   276736  Flu: The Story of the Great Influenza Pandemic...            8
4   276737                             The Mummies of Urumchi            6

In [ ]:
book_data.isna().sum()

User.ID        0
Book.Title     0
Book.Rating    0
dtype: int64

## Data Cleaning

In [ ]:
book_data=book_data.rename(columns={'User.ID':'User_ID','Book.Title':'Book_Title','Book.Rating':'Book_Rating'})

In [ ]:
book_data['User_ID'].nunique()

2182

In [ ]:
book_data_d1 =pd.pivot_table(book_data, values='Book_Rating',index='User_ID', columns='Book_Title').fillna(0)
book_data_d1

Book_Title   Jason, Madison &amp  ...  â”œ?â”¬?bermorgen.
User_ID                           ...
8                            0.0  ...             0.0
9                            0.0  ...             0.0
10                           0.0  ...             0.0
12                           0.0  ...             0.0
14                           0.0  ...             0.0
...                          ...  ...             ...
278846                       0.0  ...             0.0
278849                       0.0  ...             0.0
278851                       0.0  ...             0.0
278852                       0.0  ...             0.0
278854                       0.0  ...             0.0

[2182 rows x 9659 columns]

## Model Building : user based collaborative filtering

In [ ]:
cosine_UBCF =1-pairwise_distances(X= book_data_d1, metric='cosine')
cosine_UBCF

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
np.fill_diagonal(a=cosine_UBCF,val=0)
print(cosine_UBCF)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [ ]:
cosine_UBCF =pd.DataFrame(cosine_UBCF)
cosine_UBCF.index = book_data['User_ID'].unique()
cosine_UBCF.columns = book_data['User_ID'].unique()
cosine_UBCF

        276726  276729  276736  276737  ...  162109  162113  162121  162129
276726     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...  ...     ...     ...     ...     ...
162107     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162109     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162113     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162121     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
162129     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[2182 rows x 2182 columns]

In [ ]:
cosine_UBCF.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

In [ ]:
book_data[(book_data['User_ID']==162107) | (book_data['User_ID']==276726) ]

      User_ID               Book_Title  Book_Rating
0      276726      Classical Mythology            5
9987   162107  What's Bred in the Bone            7

In [ ]:
book_data[(book_data['User_ID']==162109) | (book_data['User_ID']==276726) ]

      User_ID               Book_Title  Book_Rating
0      276726      Classical Mythology            5
9988   162109  The Flower in the Skull           10

In [ ]:
book_data[(book_data['User_ID']==162121) | (book_data['User_ID']==276726) ]

      User_ID                                         Book_Title  Book_Rating
0      276726                                Classical Mythology            5
9990   162121                                  The Cloister Walk            7
9991   162121                                         Open Water            5
9992   162121                              The Evolution of Jane            8
9993   162121                                   AT PARADISE GATE            8
9994   162121  I Should Have Stayed Home: The Worst Trips of ...            8
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8

In [ ]:
book_data[(book_data['User_ID']==162129) | (book_data['User_ID']==276726) ]

      User_ID                    Book_Title  Book_Rating
0      276726           Classical Mythology            5
9999   162129  Kids Say the Darndest Things            6

## User_ID=(162121) & User_ID=(276726) are similar user so we can recommend  the book read by 162121 to 276726